I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/softaredev_room.rpy", line 661, in script
    if characters["lusi"]["heaarts"] > 1:
  File "game/softaredev_room.rpy", line 661, in <module>
    if characters["lusi"]["heaarts"] > 1:
KeyError: 'heaarts'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/softaredev_room.rpy", line 661, in script
    if characters["lusi"]["heaarts"] > 1:
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\ast.py", line 2115, in execute
    if renpy.python.py_eval(condition):
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1092, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\31622\Downloads\renpy-8.0.3-sdk\renpy\python.py", line 1085, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/softaredev_room.rpy", line 661, in <module>
    if characters["lusi"]["heaarts"] > 1:
KeyError: 'heaarts'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.3.22090809
Project Play 0.1
Wed Dec 14 10:58:43 2022
